/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.1.0
 *
 * Project: 'The_Udder_Project+TheUdderProject' 
 * Target:  'TheUdderProject' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l4xx.h"



#endif /* RTE_COMPONENTS_H */
